language: go
go: 1.15.x
services:
- docker
sudo: required
env:
  global:
    - secure: GHzd5D/cf/TF/1qXWGbp+6hM7J6joA2etLWgDIXNzXwdVAoPb7js5hYtXuUR+bw49l+gCo7KuNuCy1byCIJa+GXR3xwQRVxABTgq4OicR5uC0pYL8Gp0+mrZXbO+QoBimn7VUca1emx3YjWLmvDzJJL19U5Z6oL6UgNysZ3tPtpcnchPJPC2sNTHpC8bipDayARYZt6t43/JJtHtRvdJ1iQrSNTutzR+HDaV4pXEC2fMX/qYWny1W+LmIjz5RP/RALp5n0LxUQp6DeB53gG55LLzxG3Mn996ksVGqg05jbi9W34g9qkPyMU0bQS/oIWyHENYgFST8ugJcMTbL9Fask/WwsQtCMMdFACVRXHg27KhvkIRC9PJ/BjDa54uVKA13hop/QTVBeJ21yHnYcHX+W1teGbSVz/W+PunsHWa6Ser+5O4fBWNNh8w3qsChW6723Hja3LLJPHTBq8xGGjbi06mc1kYuzeHJo/LBxRWJnqS09JrgOr4LblZNkALZYviIFN2P+mL9bMT49B1KwOqgqdPt7+7arIzSPi3EjdsVzDPiDR9hLLwz/JdMm/kBQzoXJLcBULCEWeMnVKGrrvi0gL6bj/OzE8vS31bgGk3Q5oBRWjbDasSRVzGXgx4omTYhBuWZJhybzETXxnA38D2nngbX4KxfHbROjRG/TikWJc=
install:
- git submodule update --init
- go mod download
before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...
script:
- go test -short -failfast -coverprofile=coverage.txt ./...
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- make release
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AtG0ifE7V7OLBwLZo3wiNiv+zWyefVI3DF6G1kydilg4uRb/USZDnQT2fqN3iKWPuMW89TTpgsscESTM06N2HK1rDujohF5rG2rr1Uh1vRtlExPNFjNNEuir/Lf9dL37eDXYbekPC3RzIbPWX5dG7saeai7pHw0poVIaH5MFLv9gfMpF9RBqvJlaRi10nI4uo3KWcKgiRLZAteqMi3eqriEbyQ3QDhNi5YsTA1a6n3bxujQ1/ZWv8sl0Gi4fc0C5pBZjCOopY1gF9fxEyLukmbCwA4ABWIiASTU/jbbkO1GBf/ybBAn7IicofRZIJlGc381IFlpS6YIXiU6HhNzzYYsh6KilQJDh2iIcGJ85JMS3H67CEndsXUBvYjX3rqkWsKBRY4T3WEaTYZtLu6Iwn0sSku/8JjqjgeZiWXD68eddAO/4i7FgVPYm4m8hsGni29hxMST39J5I/a53zUhBO6JK5jrzfRw6ICzqSnzsSs9bjLsPGjVLFo5885s+8v/QA5L6kxZ3u8EhZerXZp9rpvb4ouEeK05KydakCAXLrWRFzJVHvnsYGRHtoE8+SdCcWiHsC3N4KIPBpGnBy3ad1PIAtkIRKlm43TzLKf+lL4He/7QSavP23k8MtgYL7tnPXbNW2szwPVwjGdg1VNaG7T/4gZ/Bj4JMIvh78b+J0i4=
  file: release/*
  on:
    tags: true
    repo: bonedaddy/go-indexed
notifications:
  email: false
cache:
  directories:
  - "$GOPATH/pkg/mod"
  - "$HOME/.cache/go-build"
