language: go
go: 1.15.x
services:
- docker
sudo: required
env:
  global:
    - secure: Sc67qHkxEU2ZCJvajsaW4o5gDl8HHuN8XkL0MqLxB5uhFIbwnIqUSOgv1YXFSLeMRb4NJvk4x5bLjFKjHI/OS+RHXlAAEmcwJtEPUbmeb2XK+SRaRal21ir74053uuNG5+3wve59XiOvb7rRINK2jHlBt+2Tq2/AKdgjKH4pkhXYmUg6u64Zkfg+JikO5PkKk3NDVYDg3PAWyl6ApnFHL/PNv1hlMCat2awY5ZW1ptzyoBy/SbdGDJ49IaxKRE9OjseGWM9fjCo8wMbKquz6xp8gHF9Tn1OTpdNXKMn3D/X31xRZU4Brh2rXkUGeg7M85o6P+4xRredQPryhi1SwNpq2u5XKZRqL6Og2Y3PgJSoPLygtbQaFfQ+Rb0zXmLf15AHMTAa0kAFuilM/5bO8VJGcydEHhhaM3HDcST47AIozXOQaXHq4+CLqHuaKutOw8JDRlxxeLlvugy1wogusz1NDmtJ5D41ZRY78FsvFZ+fqxR5nG56SNBB35B5GGQvZAlVuTSmbjv9E0e+b/4BdVvia5nWPUC/xnYe7xhQDqnpE9gGJ033RCDFuXiF4qC7RCaGpxawdKovVE0VJBScnOjIgUpQvjCgjcqOuxTxL4uSeAOcKL1ppIFwX/tPKcllsEdHdvBxvGowoJGZn9Jux8Em9wDAb1Dr6mwW11qnw+vc=
install:
- git submodule update --init
- go mod download
before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...
script:
- go test -short -failfast -coverprofile=coverage.txt ./...
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- make cli
- make docker-build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: QsNAA4l7MYcbyJ2suWjw7e6MiN95PHQFn5CWkbYOXDtQtDLP2LWQVMymK2PQGwyqsJ/lxRayv0r80hEfwtdJ3OA+wiYlJnKYfZ7K/HWZrwWSMe2QL3hajTNYI2i6adApshmbDJuAmkt8CwnqiI26xBuJBHFOrs/tQItwagGZkT0O+yfCCTbp9SEQqc5zIT94Wwt5gGHHrG/u2kUE/7IZx1KXiQDPEtT+1/Eakon23oGhyLFlE9KFV0rO8L1+q6phBNtNi/PJ7CBn5jXuUQuCZh1eO/6/uZRNr2IHLriap3YNDlTxdl3/l0JSu0XXYeiSv9BdNCkU0YvG06bohY/aPhBJV8xeIxVMNOBhG7SpJJSnVY11uQcL+N9nG2Gpiq+aMrqaqygeKRqT/+U5uU3xas7wvtTWTOvsYDv0I4GFVRbpCY1Fpo0V+daoC6NRu6hlMnA9SQVSTBGVoAoTVDRbXobqcy/c20iUoonG0M2bFK4BX/BuUtQVNiy95GGEIZevi1LRDgueXoRqlj0ZTQMw7Johh7xb0xnHUmhuUAlM++Zh4/mLLa44rsfU1M4pVBTPyhJhcwNSf2+jERsGP33jNkqE9VZBrh/hnGYJe2ALNHsYmhfLGJEnMtqmL0Bv6rPe1Qu1rZWSzi1YvohY1QMkPalcQTpa7HRKZbdeCE37zJQ=
  file_glob: true
  file: release/*
  on:
    tags: true
    repo: bonedady/go-indexed
notifications:
  email: false
cache:
  directories:
  - "$GOPATH/pkg/mod"
  - "$HOME/.cache/go-build"
