language: go
go: 1.15.x
services:
- docker
sudo: required
env:
  global:
    - secure: Sc67qHkxEU2ZCJvajsaW4o5gDl8HHuN8XkL0MqLxB5uhFIbwnIqUSOgv1YXFSLeMRb4NJvk4x5bLjFKjHI/OS+RHXlAAEmcwJtEPUbmeb2XK+SRaRal21ir74053uuNG5+3wve59XiOvb7rRINK2jHlBt+2Tq2/AKdgjKH4pkhXYmUg6u64Zkfg+JikO5PkKk3NDVYDg3PAWyl6ApnFHL/PNv1hlMCat2awY5ZW1ptzyoBy/SbdGDJ49IaxKRE9OjseGWM9fjCo8wMbKquz6xp8gHF9Tn1OTpdNXKMn3D/X31xRZU4Brh2rXkUGeg7M85o6P+4xRredQPryhi1SwNpq2u5XKZRqL6Og2Y3PgJSoPLygtbQaFfQ+Rb0zXmLf15AHMTAa0kAFuilM/5bO8VJGcydEHhhaM3HDcST47AIozXOQaXHq4+CLqHuaKutOw8JDRlxxeLlvugy1wogusz1NDmtJ5D41ZRY78FsvFZ+fqxR5nG56SNBB35B5GGQvZAlVuTSmbjv9E0e+b/4BdVvia5nWPUC/xnYe7xhQDqnpE9gGJ033RCDFuXiF4qC7RCaGpxawdKovVE0VJBScnOjIgUpQvjCgjcqOuxTxL4uSeAOcKL1ppIFwX/tPKcllsEdHdvBxvGowoJGZn9Jux8Em9wDAb1Dr6mwW11qnw+vc=
install:
- git submodule update --init
- go mod download
before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...
script:
- go test -short -failfast -coverprofile=coverage.txt ./...
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- make cli
- make docker-build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AtG0ifE7V7OLBwLZo3wiNiv+zWyefVI3DF6G1kydilg4uRb/USZDnQT2fqN3iKWPuMW89TTpgsscESTM06N2HK1rDujohF5rG2rr1Uh1vRtlExPNFjNNEuir/Lf9dL37eDXYbekPC3RzIbPWX5dG7saeai7pHw0poVIaH5MFLv9gfMpF9RBqvJlaRi10nI4uo3KWcKgiRLZAteqMi3eqriEbyQ3QDhNi5YsTA1a6n3bxujQ1/ZWv8sl0Gi4fc0C5pBZjCOopY1gF9fxEyLukmbCwA4ABWIiASTU/jbbkO1GBf/ybBAn7IicofRZIJlGc381IFlpS6YIXiU6HhNzzYYsh6KilQJDh2iIcGJ85JMS3H67CEndsXUBvYjX3rqkWsKBRY4T3WEaTYZtLu6Iwn0sSku/8JjqjgeZiWXD68eddAO/4i7FgVPYm4m8hsGni29hxMST39J5I/a53zUhBO6JK5jrzfRw6ICzqSnzsSs9bjLsPGjVLFo5885s+8v/QA5L6kxZ3u8EhZerXZp9rpvb4ouEeK05KydakCAXLrWRFzJVHvnsYGRHtoE8+SdCcWiHsC3N4KIPBpGnBy3ad1PIAtkIRKlm43TzLKf+lL4He/7QSavP23k8MtgYL7tnPXbNW2szwPVwjGdg1VNaG7T/4gZ/Bj4JMIvh78b+J0i4=
  file: release/*
  on:
    tags: true
    repo: bonedaddy/go-indexed
notifications:
  email: false
cache:
  directories:
  - "$GOPATH/pkg/mod"
  - "$HOME/.cache/go-build"
